In [3]:
"""
Problem 1
Write a function that takes a list of numbers and returns a new list containing only the even numbers, in the same order.
# Example
filter_evens([1, 2, 3, 4, 5, 6])  # → [2, 4, 6]
filter_evens([1, 3, 5])            # → []
No constraints on how you write it — just solve it however feels natural. Go! 🙂
"""


def filter_evens(nums):
    return [x for x in nums if x % 2 == 0]


print(filter_evens([1, 2, 3, 4, 5, 6]))

[2, 4, 6]


In [ ]:
"""
Problem 2
Write a function that takes a list of words and returns a dictionary mapping each word to its length.
# Example
word_lengths(["apple", "hi", "banana"])  # → {"apple": 5, "hi": 2, "banana": 6}
"""


def word_lengths(words: list) -> dict:
    return {k: len(k) for k in words}


print(word_lengths(["apple", "boy"]))

{'apple': 5, 'boy': 3}


In [11]:
"""
Problem 3
Write a function that takes a list of dictionaries, each representing a person, and returns the names of people who are 18 or older, sorted alphabetically.
# Example
people = [
    {"name": "Alice", "age": 25},
    {"name": "Bob", "age": 16},
    {"name": "Charlie", "age": 18},
]

get_adults(people)  # → ["Alice", "Charlie"]

"""


def get_adults(people: list) -> list:
    return sorted(k["name"] for k in people if k["age"] >= 18)


people = [
    {"name": "Charlie", "age": 25},
    {"name": "Bob", "age": 16},
    {"name": "Apple", "age": 18},
]
get_adults(people)

['Apple', 'Charlie']

In [15]:
"""
Problem 4
Write a function that takes a string and returns a dictionary counting how many times each character appears. Ignore spaces.
# Example
char_count("hello world")  # → {"h":1, "e":1, "l":3, "o":2, "w":1, "r":1, "d":1}
"""

from collections import defaultdict


def char_count(word: str) -> dict:
    counts = defaultdict(int)
    for c in word:
        if not c.isspace():
            counts[c] += 1
    return dict(counts)


print(char_count("hello world"))

{'h': 1, 'e': 1, 'l': 3, 'o': 2, 'w': 1, 'r': 1, 'd': 1}


In [16]:
from collections import Counter


def char_count(word: str) -> dict:
    return dict(Counter(c for c in word if not c.isspace()))


print(char_count("hello world"))

{'h': 1, 'e': 1, 'l': 3, 'o': 2, 'w': 1, 'r': 1, 'd': 1}


In [17]:
"""
Problem 5
Write a function apply_all that takes a list of functions and a value, and returns a list of results from applying each function to that value.
# Example
apply_all([str.upper, str.strip, len], "  hello  ")
# → ["  HELLO  ", "hello", 9]
"""


def apply_all(functions: list, subject) -> list:
    return [f(subject) for f in functions]


apply_all([str.upper, str.strip, len], "  hello  ")

['  HELLO  ', 'hello', 9]

In [ ]:
# Silently skips non-callables rather than exploding. Whether that's better depends on context — sometimes you want it to explode loudly so the caller knows they messed up.


def apply_all2(functions: list[callable], subject) -> list:
    return [f(subject) for f in functions if callable(f)]


apply_all2([str.upper, str.strip, len], "  hello  ")

['  HELLO  ', 'hello', 9]

In [23]:
"""
Problem 6
Write a function make_multiplier that takes a number n and returns a function that multiplies its input by n.
# Example
double = make_multiplier(2)
triple = make_multiplier(3)

double(5)   # → 10
triple(5)   # → 15
"""


def make_multiplier(n: int):
    return lambda x: x * n


double = make_multiplier(2)
triple = make_multiplier(3)
triple(5)

15

In [ ]:
"""
Problem 7
Write a function that takes a 2D NumPy array and returns a new array where every value has been normalized to the range [0,1][0, 1]
[0,1] using min-max normalization:

Handle the edge case where all values are identical.
"""

import numpy as np


def normalize(a):
    a_min = np.min(a)
    a_max = np.max(a)
    # clipping a_max - a_min to avoid division by 0. Note a_max- a_min is always positive.
    d = np.clip(a_max - a_min, a_min=1e-8, a_max=None)
    return (a - a_min) / d


A = np.array([[1, 2], [3, 4]])
normalize(A)
# → [[0.  , 0.333],
#    [0.667, 1.   ]]

In [2]:
# Feedback on 7
# The alternative is an explicit guard with np.isclose:
import numpy as np


def normalize(a):
    a_min = np.min(a)
    a_max = np.max(a)
    d = a_max - a_min
    if np.isclose(d, 0):
        return np.zeros_like(a, dtype=float)
    return (a - a_min) / d


# The difference from your clipping approach:
#                         |Clipping                                   |Explicit guard
# Edge case behavior      |Returns zeros (accidentally correct)       |Returns zeros (intentionally correct)
# Intent visible in code  |❌ Not obvious                             |✅ Clear
# Branches                |0                                          |1
# Idiomatic for ML        |✅ Common                                  |✅ Also common
# The clipping version works correctly as we just worked out — but the reason it works is subtle enough that you had to think it through. The explicit guard version is unambiguous: if the range is zero, return zeros, full stop. Anyone reading it knows exactly what happens in the edge case without having to reason about numerator/denominator interactions.
# My personal preference: explicit guard for anything you'll read again later. Clipping for tight inner loops where you want branchless code.

In [6]:
""" "
Problem 8
Without using any Python loops, write a function that takes a 2D NumPy array X of shape (m, n) and a 1D array b of shape (n,), and returns a new array where b has been subtracted from every row of X.
# Example
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])  # shape (3, 3)

b = np.array([1, 1, 1])   # shape (3,)

subtract_bias(X, b)
# → [[0, 1, 2],
#    [3, 4, 5],
#    [6, 7, 8]]
No reshaping allowed — I want to see if broadcasting handles it naturally for you.
"""


def subtract_bias(X, b):
    return X - b


X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1, 1, 1])
print(subtract_bias(X, b))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
"""
Problem 9
Without loops, write a function that takes two 1D arrays a of shape (m,) and b of shape (n,), and returns a 2D array of shape (m, n) where entry [i, j] is a[i] + b[j].
# Example
a = np.array([1, 2, 3])     # shape (3,)
b = np.array([10, 20])      # shape (2,)

outer_sum(a, b)
# → [[11, 21],
#    [12, 22],
#    [13, 23]]   # shape (3, 2)
"""


def func1(a, b):
    a = a.reshape(-1, 1)
    b = b.reshape(1, -1)
    return a + b


a = np.array([1, 2, 3])
b = np.array([10, 20])
print(func1(a, b))

[[11 21]
 [12 22]
 [13 23]]
